### PR TITLE
Added initial support for IPv6

### PR DESCRIPTION
**Pull request by Mailaender**
Discovery fails with my Fritz!Box when IPv6 is available. My attempt here sadly doesn't fix it on my end, but maybe someone more knowledgeable can build upon it.

### CODE REVIEW

**Comment by lontivero** [comment]
Thank you, @Mailaender.

**Comment by lontivero** [comment]
@Mailaender i've just added support for ipv6 and i've tested it with a fake upnp device. Sadly, i have no a real device that support ipv6. If you have one, could you verify my changes work? 
Thank you.

**Comment by Mailaender** [comment]
Current master doesn't compile for me so I can't test it:

Open.Nat/Discovery/Searcher.cs(5,5): Error CS0103: The name `CloseSockets' does not exist in the current context (CS0103) (Open.Nat)

**Comment by lontivero** [comment]
@Mailaender please apologize for the broken build. I have a green in the CI server now https://ci.appveyor.com/project/lontivero/open-nat

Could you verify the changes? I appreciate your help with this issue and your time.
Thank you

**Comment by Mailaender** [comment]
Still:

```
Open.NAT - Information > Start Discovery
Open.NAT - Information > Searching for: UpnpSearcher
Open.NAT - Information > Stop Discovery
Open.NAT - Information > Device not found. Common reasons:
Open.NAT - Information > 	* No device is present or,
Open.NAT - Information > 	* Upnp is disabled in the router or
Open.NAT - Information > 	* Antivirus software is filtering SSDP (discovery protocol).
```

Is there a way I can provide useful logging information?

**Comment by lontivero** [comment]
you can enable the logs in the **app.config** file as follow:

```
    <switches>
      <add name="System.Net" value="Warning"/>
      <add name="System.Net.Sockets" value="Verbose"/>
      <add name="Open.NAT" value="Info"/>
    </switches>
```

The important switch in this case is **System.Net.Sockets** in **Verbose"** mode. After that just run the application and share the **.\bin\[Release|Debug]\network.log** file.

If well this is standard mechanism for tracing .NET applications, i really prefer a wireshark capture with filter: ```(ip.dst == <your_router_ip> && ip.src == <your_computer_local_ip>) || ((ip.dst == <your_computer_local_ip> && ip.src == <your_router_ip>)```
Of course you need other filters in order to avoid sharing internal dns traffic and others like that.

**Comment by Mailaender** [comment]
https://gist.github.com/Mailaender/66829761022d122c4f4c32f7e876e6ff
Not sure if this is a Mono problem or something related to our code though.

Running this on:
```
mono --version
Mono JIT compiler version 4.4.2 (Stable 4.4.2.11/f72fe45 Fri Sep  2 20:31:35 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by Mailaender** [comment]
Might be related to https://bugzilla.xamarin.com/show_bug.cgi?id=6057

**Comment by Mailaender** [comment]
Nope, still doesn't work on Mono 4.6.0 where it is supposed to be fixed.

The **app.config** file doesn't seem to do much. I still only get basic info in network.log:

```
Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : Device not found. Common reasons:
Open.NAT Information: 0 : 	* No device is present or,
Open.NAT Information: 0 : 	* Upnp is disabled in the router or
Open.NAT Information: 0 : 	* Antivirus software is filtering SSDP (discovery protocol).
```

plus a crash https://github.com/lontivero/Open.NAT/issues/56 when I run it in the command line.

**Pull request merged**
